export enum AppRole {
  DOCTOR = "DOCTOR",
  SPECIALIST = "SPECIALIST",
  NURSE = "NURSE",
  MEDICAL_STUDENT = "MEDICAL_STUDENT",
  HOSPITAL = "HOSPITAL",
  CLINIC = "CLINIC",
  RESEARCHER = "RESEARCHER",
  HEALTHCARE_RECRUITER = "HEALTHCARE_RECRUITER",
  HEALTHCARE_COMPANY = "HEALTHCARE_COMPANY",
  MEDICAL_DEVICE_COMPANY = "MEDICAL_DEVICE_COMPANY",
  ADMIN = "ADMIN",
}
